networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
  wan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  victim:
    image: alpine
    container_name: victim
    networks:
      lan:
        ipv4_address: 192.168.10.10
    command: sh -c "apk add --no-cache curl && sleep infinity"
    cap_add:
      - NET_ADMIN

  attacker:
    image: kalilinux/kali-rolling
    container_name: attacker
    networks:
      lan:
        ipv4_address: 192.168.10.99
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true

  router:
    image: alpine
    container_name: router
    networks:
      lan:
        ipv4_address: 192.168.10.2
      wan:
        ipv4_address: 10.0.0.2
    command: sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward && sleep infinity"
    cap_add:
      - NET_ADMIN

  webserver:
    image: nginx
    container_name: webserver
    networks:
      wan:
        ipv4_address: 10.0.0.10
